### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by Shoebtamboli** [arabian9ts/SSD300#14]
@arabian9ts hey do you have a test.py or anything. I have trained it and want to test it. I am new to tensorflow and not much knowledge of how to write one test file.

If you have anything please let me know?

**Comment by arabian9ts** [comment]
@Shoebtamboli Hi. Now, you can test with 
`pred_confs, pred_locs = ssd.eval(images, actual_data=None, is_training=False)`
and this is in draw_marker func(train.py line at 61)
`ssd.eval` returns predicted locations and its label if `is_training` is False.
(if not, eval func returns those and 3 losses such as location loss)
This implementation is not good because returns vary according to `is_training`.
However, as this is still under implementation, I'm doing that.

If you use voc2007 images, you can test simply as following.
`$ python train.py 000001.jpg`

**Comment by Shoebtamboli** [comment]
tested it.. thanks
